# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flavors' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Pods for Flavors
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/'
  # pod 'RNVectorIcons.', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # pod 'RNScreens', :path => '../node_modules/react-native-screens'

  # pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end