# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flavors' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Flavors
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end


